# Site settings
title: Rob Gabbard
firstname: Rob
lastname: Gabbard
email: someone@somewhere.com
url: http://robgabbard.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 355b71 #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 2c3e50 #A2122F

# Footer settings
footer:
  location: Primary Location
  social: Contact Information

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/robgabbard
  - title: twitter
    url: http://twitter.com/rgabbard
#title: github
#    url: http://github.com/rgabbard

# Postal address (add as many lines as necessary)
#address:
#  - line: Somewhere, USA

# Build settings
markdown: kramdown
permalink: pretty
